#!/usr/bin/env python3
"""
tools/extract_weights.py
========================
Extracts and quantizes PyTorch Siamese-SNN weights from PFL-SNN-BACKEND
into a C++ PROGMEM header file (model_weights.h) for ESP32-S3 N16R8.

Features:
  - Quantizes weights to int8 (symmetric linear quantization with scale factor).
  - Exports weight structures and scaling parameters as PROGMEM arrays.
  - Provides skeleton weights if no checkpoint file is found.

Usage:
  python tools/extract_weights.py \
      --checkpoint outputs/models/siamese_snn_best.pt \
      --output PFL_SNN_ESP32/model_weights.h \
      --in-channels 1 \
      --enc-channels 8 16 32 64
"""

import os
import sys
import argparse
import numpy as np

# Add project root to sys.path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

try:
    import torch
    import torch.nn as nn
    HAS_TORCH = True
except ImportError:
    HAS_TORCH = False

def quantize_to_int8(tensor_np: np.ndarray):
    """Symmetric per-tensor int8 quantization."""
    t = tensor_np.astype(np.float32)
    max_val = np.abs(t).max()
    if max_val == 0 or np.isnan(max_val):
        return np.zeros_like(t, dtype=np.int8), 1.0
    scale = float(max_val / 127.0)
    q = np.clip(np.round(t / scale), -128, 127).astype(np.int8)
    return q, scale

def format_c_array(name: str, arr: np.ndarray, dtype_str: str = "int8_t", progmem: bool = True) -> str:
    """Format numpy array into C PROGMEM array string."""
    flat = arr.flatten()
    pm = "PROGMEM " if progmem else ""
    if dtype_str == "int8_t":
        vals_str = ", ".join(str(int(v)) for v in flat)
    else:
        vals_str = ", ".join(f"{float(v):.6f}f" for v in flat)
    
    return f"static const {dtype_str} {pm}{name}[{len(flat)}] = {{\n  {vals_str}\n}};\n\n"

def main():
    parser = argparse.ArgumentParser(description="Extract & Quantize SNN Weights for ESP32-S3")
    parser.add_argument("--checkpoint", default="outputs/models/siamese_snn_best.pt")
    parser.add_argument("--output", default="PFL_SNN_ESP32/model_weights.h")
    parser.add_argument("--in-channels", type=int, default=1)
    parser.add_argument("--enc-channels", type=int, nargs="+", default=[8, 16, 32, 64])
    args = parser.parse_args()

    print(f"[Exporter] Target output: {args.output}")
    print(f"[Exporter] Config: input_ch={args.in_channels}, enc_ch={args.enc_channels}")

    state_dict = {}
    if HAS_TORCH and os.path.exists(args.checkpoint):
        print(f"[Exporter] Loading PyTorch checkpoint: {args.checkpoint}")
        try:
            state_dict = torch.load(args.checkpoint, map_location="cpu")
            if "state_dict" in state_dict:
                state_dict = state_dict["state_dict"]
        except Exception as e:
            print(f"[Exporter] Warning: Failed to load checkpoint ({e}). Generating fallback parameters.")
            state_dict = {}
    else:
        print("[Exporter] Checkpoint not found or PyTorch unavailable. Generating quantized initialized arrays.")

    lines = [
        "// model_weights.h — Auto-generated by tools/extract_weights.py\n",
        "// Embedded Quantized (int8) Weights for ESP32-S3 LIF SNN Engine\n",
        "#pragma once\n",
        "#include <pgmspace.h>\n",
        "#include <stdint.h>\n\n"
    ]

    # Helper function to get array or random fallback
    def get_layer_data(key, shape, std=0.05):
        if key in state_dict and isinstance(state_dict[key], torch.Tensor):
            return state_dict[key].detach().cpu().numpy()
        else:
            np.random.seed(abs(hash(key)) % (2**32 - 1))
            return np.random.normal(0, std, size=shape).astype(np.float32)

    # 1. Encoder Weights
    channels = [args.in_channels] + args.enc_channels
    for i in range(len(args.enc_channels)):
        in_c = channels[i]
        out_c = channels[i+1]
        
        # Conv1
        w1 = get_layer_data(f"encoder.encoder_blocks.{i}.conv_block.0.weight", (out_c, in_c, 3, 3))
        q1, s1 = quantize_to_int8(w1)
        lines.append(format_c_array(f"enc{i}_conv1_w", q1, "int8_t"))
        lines.append(f"static const float enc{i}_conv1_scale = {s1:.8f}f;\n\n")

        # BN1
        gamma1 = get_layer_data(f"encoder.encoder_blocks.{i}.conv_block.1.weight", (out_c,), 1.0)
        beta1  = get_layer_data(f"encoder.encoder_blocks.{i}.conv_block.1.bias", (out_c,), 0.0)
        mean1  = get_layer_data(f"encoder.encoder_blocks.{i}.conv_block.1.running_mean", (out_c,), 0.0)
        var1   = get_layer_data(f"encoder.encoder_blocks.{i}.conv_block.1.running_var", (out_c,), 1.0)
        lines.append(format_c_array(f"enc{i}_bn1_gamma", gamma1, "float", progmem=True))
        lines.append(format_c_array(f"enc{i}_bn1_beta",  beta1,  "float", progmem=True))
        lines.append(format_c_array(f"enc{i}_bn1_mean",  mean1,  "float", progmem=True))
        lines.append(format_c_array(f"enc{i}_bn1_var",   var1,   "float", progmem=True))

        # Conv2
        w2 = get_layer_data(f"encoder.encoder_blocks.{i}.conv_block.3.weight", (out_c, out_c, 3, 3))
        q2, s2 = quantize_to_int8(w2)
        lines.append(format_c_array(f"enc{i}_conv2_w", q2, "int8_t"))
        lines.append(f"static const float enc{i}_conv2_scale = {s2:.8f}f;\n\n")

        # BN2
        gamma2 = get_layer_data(f"encoder.encoder_blocks.{i}.conv_block.4.weight", (out_c,), 1.0)
        beta2  = get_layer_data(f"encoder.encoder_blocks.{i}.conv_block.4.bias", (out_c,), 0.0)
        mean2  = get_layer_data(f"encoder.encoder_blocks.{i}.conv_block.4.running_mean", (out_c,), 0.0)
        var2   = get_layer_data(f"encoder.encoder_blocks.{i}.conv_block.4.running_var", (out_c,), 1.0)
        lines.append(format_c_array(f"enc{i}_bn2_gamma", gamma2, "float", progmem=True))
        lines.append(format_c_array(f"enc{i}_bn2_beta",  beta2,  "float", progmem=True))
        lines.append(format_c_array(f"enc{i}_bn2_mean",  mean2,  "float", progmem=True))
        lines.append(format_c_array(f"enc{i}_bn2_var",   var2,   "float", progmem=True))

    # 2. Bottleneck Weights
    bot_in = args.enc_channels[-1]
    bot_out = bot_in * 2
    w_bot = get_layer_data("encoder.bottleneck.0.weight", (bot_out, bot_in, 3, 3))
    qb, sb = quantize_to_int8(w_bot)
    lines.append(format_c_array("bot_conv1_w", qb, "int8_t"))
    lines.append(f"static const float bot_conv1_scale = {sb:.8f}f;\n\n")
    lines.append(format_c_array("bot_bn1_gamma", get_layer_data("encoder.bottleneck.1.weight", (bot_out,), 1.0), "float"))
    lines.append(format_c_array("bot_bn1_beta",  get_layer_data("encoder.bottleneck.1.bias", (bot_out,), 0.0), "float"))
    lines.append(format_c_array("bot_bn1_mean",  get_layer_data("encoder.bottleneck.1.running_mean", (bot_out,), 0.0), "float"))
    lines.append(format_c_array("bot_bn1_var",   get_layer_data("encoder.bottleneck.1.running_var", (bot_out,), 1.0), "float"))

    # 3. Decoder Weights (Reverse order)
    dec_channels = list(reversed(args.enc_channels))
    in_ch = bot_out
    for i in range(len(dec_channels)):
        out_ch = dec_channels[i]
        
        # Up-conv
        w_up = get_layer_data(f"decoder.decoder_blocks.{i}.upsample.weight", (in_ch, out_ch, 2, 2))
        qup, sup = quantize_to_int8(w_up)
        lines.append(format_c_array(f"dec{i}_up_w", qup, "int8_t"))
        lines.append(f"static const float dec{i}_up_scale = {sup:.8f}f;\n\n")

        # Conv1 (post concat: out_ch + skip_ch = out_ch * 2)
        w_dec1 = get_layer_data(f"decoder.decoder_blocks.{i}.conv1.0.weight", (out_ch, out_ch * 2, 3, 3))
        qd1, sd1 = quantize_to_int8(w_dec1)
        lines.append(format_c_array(f"dec{i}_conv1_w", qd1, "int8_t"))
        lines.append(f"static const float dec{i}_conv1_scale = {sd1:.8f}f;\n\n")
        lines.append(format_c_array(f"dec{i}_bn1_gamma", get_layer_data(f"decoder.decoder_blocks.{i}.conv1.1.weight", (out_ch,), 1.0), "float"))
        lines.append(format_c_array(f"dec{i}_bn1_beta",  get_layer_data(f"decoder.decoder_blocks.{i}.conv1.1.bias", (out_ch,), 0.0), "float"))
        lines.append(format_c_array(f"dec{i}_bn1_mean",  get_layer_data(f"decoder.decoder_blocks.{i}.conv1.1.running_mean", (out_ch,), 0.0), "float"))
        lines.append(format_c_array(f"dec{i}_bn1_var",   get_layer_data(f"decoder.decoder_blocks.{i}.conv1.1.running_var", (out_ch,), 1.0), "float"))

        in_ch = out_ch

    # 4. Output Conv (1x1 to 2 classes)
    out_w = get_layer_data("decoder.output_conv.weight", (2, args.enc_channels[0], 1, 1))
    qo, so = quantize_to_int8(out_w)
    lines.append(format_c_array("out_conv_w", qo, "int8_t"))
    lines.append(f"static const float out_conv_scale = {so:.8f}f;\n\n")
    lines.append(format_c_array("out_conv_bias", get_layer_data("decoder.output_conv.bias", (2,), 0.0), "float", progmem=False))

    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, "w") as f:
        f.writelines(lines)

    print(f"[Exporter] Successfully exported model weights to: {args.output}")

if __name__ == "__main__":
    main()
